name: Deploy GH:Pages

on:
  push:
    branch: main

jobs:
  build_and_deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

      - uses: actions/setup-node@v3
        with:
          node-version: '14'
      - run: npm install

      - name: Build
        run: npm run build

      - name: Create repo
        run: |
          cd dist
          git config --global init.defaultBranch main
          git config --global user.email "lorennorman@gmail.com"
          git config --global user.name "Loren Norman"
          git init
          git add -A
          git commit -m 'deploy'

      - name: Force Push to gh-pages
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true

          # run: git push -f git@github.com:lorennorman/p2p-play.git main:gh-pages
